player createDiaryRecord ["Diary", ["Credits","Some people outside of mission maker team helped creating this!<br/><br/>
audiocustoms - Fantastic voice work and sound editing!"]];

player createDiaryRecord ["Diary", ["Persistence", "When disconnecting or crashing your current character's progress will be saved. Meaning you can join again after technical difficulties and continue where you left off"]];

player createDiaryRecord ["Diary", ["Respawn", "No respawn unless Arma does something weird."]];

player createDiaryRecord ["Diary", ["Hunger and Thirst", "You have to keep yourself fed and hydrated. Find edibles in the field and collect them. If you fail to do so, you will most likely die."]];

player createDiaryRecord ["Diary", ["Two main weapons", "You can hold two main weapons, well not at the same time, but you can switch between them with an ACE self action under the 'Equipment' category. Be warned tho, trying to duplicate stuff will result in punishment!"]];

player createDiaryRecord ["Diary", ["MSR towards the town", "The MSR leading towards the town became somewhat legendary, due to all the rumors around it. A little while after the evacuation the MSR quickly filled up and caused an avalanche of vehicles being stuck, waiting to be allowed into the town. This traffic jam never cleared as the military eventually unleashed a chemical attack in the area.<br/><br/>Scavengers desperate enough to wander the road say that they saw ghosts of people sitting in their cars waiting to get into the town or ghosts walking towards the checkpoint leaving behind their vehicles. The few returning claim the village is still full of loot. As far as we know, we are some of the only ones brave enough to try to go there after the incident. Our local science man Alexuh back in our base camp told us due to the trees forming a wind aisle it is the best way to get to the town. The wind carries away most chemical residue making the trip a lot safer after the wind calmed down. Since it is summer, there is no wind or just a very slight one, meaning it is possible to traverse the road with masks and oxygen tanks. Besides, the forest is littered with mines. However that also means the chances of running into other scavengers are higher, no way to get around them without either dying from mines or chemicals."]];

player createDiaryRecord ["Diary", ["Scouting", "Before you head out, you took some precautions, Andrey and Valery scouted ahead and gathered some information about the area east of you.<br/><br/><br/><br/>Up the hill towards the north east seems to be a singular house that they could not approach as their threat-meter raised to dangerous levels. And even further to the east, they found out that you are not the only group trying to reach the town, there is another, larger group present in Wrzeszcz. You do not know that groups name, but they all dress in black despite it being extremely hot in the summer. Andrey and Valery also reported that they’ve seen some of them carry around oxygen tanks.<br/><br/><br/><br/>There also seems to be some unknowns in the area as well. Fresh deep tracks in the dirt, much like from a heavy construction vehicle were found. Alongside the tracks there were several footprints, matching marching boots that lead into a red zone. Who ever that is must have access to full CBRN suits."]];

player createDiaryRecord ["Diary", ["Finite resources", "Resources are scarce by design, they are also finite. This applies to items, guns, ammo, water and everything you can find in the area. Make sure to use everything you can find, be it in the wild or on some poor sods body."]];

player createDiaryRecord ["Diary", ["CBRN Mechanic",
"This Mission will feature several CBRN mechanics! For one all of you will have gas masks in your backpacks as there will be many areas you NEED these. There is CBRN related damage, you can check on your approximate health via ACE self interacting -> Medical -> Check CBRN Exposure.<br/><br/>Warning CBRN exposure will never vanish in this mission, it takes days to get rid of it, so it is not simulated! Be careful and do not soak up too much! If you soak up too much a vicious cycle will start and the exposure will constantly rise. It will continue to rise even in non exposed areas until you use a decontamination shower. You will be notified when this happens!<br/><br/>If you exceed the maximum threshold you will die, flat out.<br/><br/>Oxygen in backpack tanks are finite! Once the air runs out they are useless, constantly keep checking your tanks air pressure! The tank will beep 3 times if your remaining air is below 5 minutes, it will sound a constant tone for 10 seconds when you reach 30 seconds left. You can switch out an oxygen tank while oxygen is still running without the oxygen supply to dry up.<br/><br/>People with a MicroDagr can open up a threat monitor. It will appear at the top of the screen. The threat meter is rainbow color coded, going from Green to Yellow to Orange to Red, indicating the threat level. Each level is additive and need the previous requirements!<br/><br/>Threat level 1 (Green): No Mask needed<br/><br/>Threat level 2 (Yellow): Mask needed<br/><br/>Threat level 3 (Orange): Fresh oxygen supply needed<br/><br/>Threat level 4 (Red): Full CBRN suit<br/><br/>Any threat level above cannot be displayed on the threat meter, it is kind of the equivalent of 3.6 rontgen."]];

player createDiaryRecord ["Diary", ["Wildlife and area of operation",
"The area around Gieraltow, as well as many other areas in Livonia, has little to no wildlife with the exception of some birds. This makes the whole area eerily quiet.<br/><br/>It is summer, July to be exact and due to global warming you can easily expect 50°C, you’ll need to stay hydrated!<br/><br/>Overcast will have some clouds. The sun would make its way through if it weren’t for the high amount of dust and smoke in the area.There even seems to be a wild fire some miles off.<br/><br/>Expectancy of rain: 0%. Like in the last 3 years, it will most likely not rain much, if at all between June and end of September.<br/><br/>The area of operation is mostly woodland, except for Gieraltow, which will be more urban. The immediate area around Gieraltow will be difficult to travers, as there are multiple dangers like mines scattered around.<br/><br/>The MSR towards the town is blocked by defunct vehicles from the original evacuation plan. It is possible to get through with a car, but it will take some time and a lot of maneuvering."]];

player createDiaryRecord ["Diary", ["Tasks", "1. Scavenge the area, your main group needs all the resources you can find!<br/><br/>
2. Find filled Oxygen Tanks in order to scavenge Gieraltow<br/><br/>
3. Scavenge as much as possible from Gieraltow<br/><br/>4. Do not die, your group needs you!<br/><br/>(Optional) Your truck is probably about to break down. Find a car you can bring back<br/><br/>(Optional) Find out if there is a livable area to settle in nearby"]];

player createDiaryRecord ["Diary", ["General Information", "The year is 2037, the earth has heated up tremendously and several intermediate wars have broken out to secure food and water. The country of Livonia is no exception to this. People are scavenging for supplies and weapons to survive as the local government tries to preserve itself and its military while the population is starving and slowly dying off in the heat of the summer.<br/><br/>Many nations including Livonia even used chemical weapons to create restricted zones around important areas, which can not be entered without CBRN equipment. Mainly to restrict the populations access to supplies like food and water and keep the governments alive and in charge.<br/><br/><br/><br/>Now, 5 years after this incident resources have become extremely scarce and supplies that don’t expire such as honey, have become worth more than gold. The good news is that stories  tell about a town called Gieraltow, that is located right at the edge of a massive ring shaped zone, which supposedly has a lot of loot left in the area of the town that requires fresh oxygen tanks and masks in order to survive. Your group of scavengers make their way there, trying to survive against the heat and other groups of scavengers."]];