player createDiaryRecord ["Diary", ["Additional information","The blizzard will arrive in around 1 hour and 30 minutes, you can check the current estimate via ace self-interaction.<br/><br/>Due to the harsh environment equipment issued so spec ops are MP7s for CQC, HK416s for SQLs and AR, a Mk 11 for the marksman and an autonomous UAV of type Stomper as pack mule.<br/><br/>The stomper will hold ammo, medical and telescopic ladders. You will also be able to ride on the stomper, just ace interact with different positions.<br/><br/>Large vehicles are not possible in this environment, the largest vehicles available are small trucks.<br/><br/>The Chinese noticed their security equipment does not withstand the harsh environment in the long term, thus they are using guard dogs and manual sirens as alarms. This means it is possible to prevent a base alarm by not allowing them to reach a loudspeaker pole, however unsuppressed gun fire will most likely alert the surrounding personnel.<br/><br/>It is possible to hold up enemies by sneaking up on their back and prompting them to “Freeze” in a gravelly voice."]];

player createDiaryRecord ["Diary", ["Persistence", "When disconnecting or crashing your current character's progress will be saved. Meaning you can join again after technical difficulties and continue where you left off"]];

player createDiaryRecord ["Diary", ["Respawn", "No respawn unless Arma does something weird."]];

player createDiaryRecord ["Diary", ["Hunger and Thirst", "You have to keep yourself fed and hydrated. Find editables in the field and collect them. If you fail to do so, you will most likely die."]];

player createDiaryRecord ["Diary", ["Two main weapons", "You can hold two main weapons, well not at the same time, but you can switch between them with an ACE self action under the 'Equipment' category. Be warned tho, trying to duplicate stuff will result in punishment!"]];

player createDiaryRecord ["Diary", ["MSR towards the town", "The MSR leading towards the town became somewhat legendary, due to all the rumors around it. A little while after the evacuation the MSR quickly filled up and caused an avalanche of vehicles being stuck, waiting to be allowed into the town. This traffic jam never cleared as the military eventually unleashed a chemical attack in the area.<br/>
Scavengers desperate enough to wander the road say that they saw ghosts of people sitting in their cars waiting to get into the town or ghosts walking towards the checkpoint leaving behind their vehicles. The few returning claim the village is still full of loot. As far as we know, we are some of the only ones brave enough to try and go there after the incident. Our local science man Alexuh back in our  base camp told us due to the trees forming a wind aisle it is the best way to get to the town. The wind carries away most chemical residue making the trip a lot safer after the wind calmed down. Since it is summer, there is no wind or just a very slight one, meaning it is possible to traverse the road with masks and oxygen tanks. Besides, the forest is littered with mines. However that also means the chances of running into other scavengers are higher, no way to get around them without either dying from mines or chemicals."]];

player createDiaryRecord ["Diary", ["Scouting", "Before you head out, you took some precautions, Andrey and Valery scouted ahead and gathered some information about the area east of you.<br/><br/>
Up the hill towards the north east seems to be a singular house that they could not approach as their threat-meter raised to dangerous levels. And even further to the east they found out that you are not the only group trying to reach the town, there is another, larger group present in Wrzeszcz. You do not know that groups name, but they all dress in black despite it being extremely hot in the summer. Andrey and Valery also reported that they’ve seen some of them carry around oxygen tanks.<br/><br/>
There also seems to be some unknowns in the area as well. Fresh deep tracks in the dirt, much like from a heavy construction vehicle were found. Alongside the tracks there were several footprints, matching marching boots that lead into a red zone. Who ever that is must have access to full CBRN suits."]];

player createDiaryRecord ["Diary", ["Finite resources", "Resources are scarce by design, they are also finite. This applies to items, guns, ammo, water and everything you can find in the area. Make sure to use everything you can find, be it in the wild or on some poor sods body."]];

player createDiaryRecord ["Diary", ["CBRN Mechanic",
"This Mission will feature several CBRN mechanics! For one all of you will have gas masks in your backpacks as there will be many areas you NEED these. There is CBRN related damage, you can check on your approximate health when ACE self interacting -> Medical -> Check CRBN Exposure.<br/>
Warning CBRN exposure will never vanish in this mission, it takes days to get rid of it, so it is not simulated! Be careful and do not soak up too much! If you soak up too much a vicious cycle will start and the exposure will constantly rise. It will continue to rise even in non exposed areas until you use a decontamination shower. You will be notified when this happens!<br/>
If you exceed the maximum threshold you will die, flat out.<br/>
Oxygen in backpack tanks are finite! Once the air runs out they are useless, constantly keep checking your tanks air pressure! The tank will beep 3 times if your remaining air is below 5 minutes, it will sound a constant tone for 10 seconds when you reach 30 seconds left.<br/>
People with a MicroDagr can open up a threat monitor. It will appear at the top of the screen. The threat meter is rainbow color coded, going from Green to Yellow to Orange to Red, indicating the threat level. Each level is additive and need the previous requirements!<br/>
Threat level 1 (Green): No Mask needed<br/>
Threat level 2 (Yellow): Mask needed<br/>
Threat level 3 (Orange): Fresh oxygen supply needed<br/>
Threat level 4 (Red): Full CBRN suit<br/>
Any threat level above cannot be displayed on the threat meter, it is kind of the equivalent of 3.6 rontgen."]];

player createDiaryRecord ["Diary", ["Objective", "This is a stealth mission, stay undetected as long as possible!<br/><br/>Gain information about the base Jinping by infiltrating the camp labeled Xiaojian<br/><br/>Enter base Jinping undetected and extract Dr. P. Julian and his documents<br/><br/>Exfil to the east<br/>"]];

player createDiaryRecord ["Diary", ["General Information", "This is an infiltration mission to extract information and personnel from a Chinese base located in the Antarctic.<br/><br/>The Chinese government started to aggressively expand their territory in the Antarctic despite every nation on earth agreed that the Antarctic belongs to everyone. Right now, the area spans several hundred kilometers wide and is dotted with several small camps used as reason to keep the occupied land. This made many nations uneasy how to approach China about it.<br/><br/>Recent satellite footage suggests that the Chinese are deploying troops now into the Antarctic, most of them are currently stationed in the base known as Jinping. But it also shows they are distributing personnel to camps surrounding the base. These camps received several upgrades such as field domes and unknown large equipment in them. It is suspected that China is ramping up their oil production in the Antarctic as the base Jinping showed oil probing towers, oil pumps and several large domes as well.<br/><br/><br/>However, this not the main reason for this infiltration operation. China employed the Bio Chemist Dr. P. Julian with a doctorate on the topic of “Engineering Organic Components of Parasites”. This does not match up with oil production and concerns were issued that maybe China is pumping up more than just oil. Our government issued order to capture the doctor and extract as much information from the base as possible.<br/><br/>This sparked this quick snatch and grab infiltration operation. 12 Spec ops are being deployed to infiltrate via land at night. Gather information about the base Jinping at a nearby camp, infiltrate the base, extract the doctor and try to steal information on what they are surfacing.<br/><br/>All under a race against and approaching blizzard used to cover the exfil."]];